require 'yaml'

current_dir    = File.dirname(File.expand_path('../', Dir.pwd))
configs        = YAML.load_file("#{current_dir}/config.yaml")
# Note: Remember to add the 'chef.json' properties to the cleanup chef recipe
vm_username = configs['credentials']['vm_username']
vm_password = configs['credentials']['vm_password']
network_share_smb_domain = configs['credentials']['smb_domain']
network_share_smb_username = configs['credentials']['smb_username']
network_share_smb_password = configs['credentials']['smb_password']
network_share_smb_domain_and_username = "#{network_share_smb_domain}\\#{network_share_smb_username}"
relativity_smtp_server = configs['email']['smtp_server']
relativity_smtp_port = configs['email']['smtp_port']
relativity_email_from = configs['email']['email_from']
relativity_email_to = configs['email']['email_to']

Vagrant.configure('2') do |config|
  config.vm.define 'RelativityDevVm'
  config.berkshelf.enabled = true
  config.berkshelf.berksfile_path = 'Cookbooks\\Relativity\\Berksfile'

  # Name of box to install with
  config.vm.box = 'DevVmBaseImage'

  # Communicator type
  config.vm.communicator = 'winrm'

  # Guest OS
  config.vm.guest = :windows
  config.windows.halt_timeout = 15

  # Config networks on guest.
  config.vm.network :forwarded_port, guest: 3389, host: 3389, id: 'rdp', auto_correct: true
  config.vm.network :forwarded_port, guest: 22, host: 2222, id: 'ssh', auto_correct: true
  config.vm.network :forwarded_port, guest: 5985, host: 5985, id: 'winrm', auto_correct:true

  # Admin user name and password
  config.winrm.username = vm_username
  config.winrm.password = vm_password

  # Hyperv configuration
  config.vm.provider :hyperv do |h|
    h.vmname = 'RelativityDevVm'
    h.cpus = 4
    h.memory = 16000
  end

  config.vm.synced_folder '.', '/vagrant',
  disabled: false,
  smb_username: network_share_smb_domain_and_username,
  smb_password: network_share_smb_password

  ######################### Chef Recipes #########################
  # Setup Log file
  config.vm.provision 'chef_zero' do |chef|
    chef.cookbooks_path = 'Cookbooks'
    chef.data_bags_path = 'DataBags'
    chef.nodes_path = 'Nodes'
    chef.roles_path = 'Roles'
    chef.channel = 'stable'
    chef.version = '13.8.5'
    chef.json = {
      'smb_domain' => network_share_smb_domain,
      'smb_username' => network_share_smb_username,
      'smb_password' => network_share_smb_password,
      'smtp_server' => relativity_smtp_server,
      'smtp_port' => relativity_smtp_port,
      'email_from' => relativity_email_from,
      'email_to' => relativity_email_to,
    }
    chef.add_recipe('Relativity::default_setup_log_file')
  end

   # Create Base Image - Part-1
   config.vm.provision 'chef_zero' do |chef|
    chef.cookbooks_path = 'Cookbooks'
    chef.data_bags_path = 'DataBags'
    chef.nodes_path = 'Nodes'
    chef.roles_path = 'Roles'
    chef.channel = 'stable'
    chef.version = '13.8.5'
    chef.json = {
      'smb_domain' => network_share_smb_domain,
      'smb_username' => network_share_smb_username,
      'smb_password' => network_share_smb_password,
      'smtp_server' => relativity_smtp_server,
      'smtp_port' => relativity_smtp_port,
      'email_from' => relativity_email_from,
      'email_to' => relativity_email_to,
    }
    chef.add_recipe('BaseImage::pre_windows_change_computer_name')
    chef.add_recipe('BaseImage::pre_windows_install_nuget_provider')
    chef.add_recipe('BaseImage::pre_windows_create_default_folders')
    chef.add_recipe('BaseImage::windows_set_explorer_properties')
    chef.add_recipe('BaseImage::windows_set_auto_login')
    chef.add_recipe('BaseImage::windows_disable_firewall')
    chef.add_recipe('BaseImage::windows_give_background_processes_priority')
    chef.add_recipe('BaseImage::windows_install_software')
    chef.add_recipe('BaseImage::windows_add_programs_to_taskbar')
    chef.add_recipe('BaseImage::pre_relativity_create_shared_folders')
    chef.add_recipe('BaseImage::pre_relativity_install_windows_features_and_services')
    chef.add_recipe('BaseImage::pre_relativity_install_windows_update_for_service_bus_defect')
    chef.add_recipe('BaseImage::pre_relativity_install_sqlserver')
  end

  # Restart VM
  config.vm.provision :reload

   # Create Base Image - Part-2
   config.vm.provision 'chef_zero' do |chef|
    chef.cookbooks_path = 'Cookbooks'
    chef.data_bags_path = 'DataBags'
    chef.nodes_path = 'Nodes'
    chef.roles_path = 'Roles'
    chef.channel = 'stable'
    chef.version = '13.8.5'
    chef.json = {
      'smb_domain' => network_share_smb_domain,
      'smb_username' => network_share_smb_username,
      'smb_password' => network_share_smb_password,
      'smtp_server' => relativity_smtp_server,
      'smtp_port' => relativity_smtp_port,
      'email_from' => relativity_email_from,
      'email_to' => relativity_email_to,
    }
    chef.add_recipe('BaseImage::pre_relativity_install_servicebus')
  end

  # # Restart VM
  # config.vm.provision :reload

  # # Run Pre-Windows Chef Recipe
  # config.vm.provision 'chef_zero' do |chef|
  #   chef.cookbooks_path = 'Cookbooks'
  #   chef.data_bags_path = 'DataBags'
  #   chef.nodes_path = 'Nodes'
  #   chef.roles_path = 'Roles'
  #   chef.channel = 'stable'
  #   chef.version = '13.8.5'
  #   chef.json = {
  #     'smb_domain' => network_share_smb_domain,
  #     'smb_username' => network_share_smb_username,
  #     'smb_password' => network_share_smb_password,
  #     'smtp_server' => relativity_smtp_server,
  #     'smtp_port' => relativity_smtp_port,
  #     'email_from' => relativity_email_from,
  #     'email_to' => relativity_email_to,
  #   }
  #   chef.add_recipe('Relativity::default_delete_script_result_file')
  #   chef.add_recipe('Relativity::initial_setup_write_relativity_invariant_version_to_log_file_copy_file')
  # end

  # # Write Relativity and Invariant Version Numbers to log file
  # config.vm.provision 'chef_zero' do |chef|
  #   chef.cookbooks_path = 'Cookbooks'
  #   chef.data_bags_path = 'DataBags'
  #   chef.nodes_path = 'Nodes'
  #   chef.roles_path = 'Roles'
  #   chef.channel = 'stable'
  #   chef.version = '13.8.5'
  #   chef.json = {
  #     'smb_domain' => network_share_smb_domain,
  #     'smb_username' => network_share_smb_username,
  #     'smb_password' => network_share_smb_password,
  #     'smtp_server' => relativity_smtp_server,
  #     'smtp_port' => relativity_smtp_port,
  #     'email_from' => relativity_email_from,
  #     'email_to' => relativity_email_to,
  #   }
  #   chef.add_recipe('Relativity::initial_setup_write_relativity_invariant_version_to_log_file_write_to_file')
  # end

  # # Restart VM
  # config.vm.provision :reload

  # # Run Pre-Relativity Copy Response Files Chef Recipe
  # config.vm.provision 'chef_zero' do |chef|
  #   chef.cookbooks_path = 'Cookbooks'
  #   chef.data_bags_path = 'DataBags'
  #   chef.nodes_path = 'Nodes'
  #   chef.roles_path = 'Roles'
  #   chef.channel = 'stable'
  #   chef.version = '13.8.5'
  #   chef.json = {
  #     'smb_domain' => network_share_smb_domain,
  #     'smb_username' => network_share_smb_username,
  #     'smb_password' => network_share_smb_password,
  #     'smtp_server' => relativity_smtp_server,
  #     'smtp_port' => relativity_smtp_port,
  #     'email_from' => relativity_email_from,
  #     'email_to' => relativity_email_to,
  #   }
  #   chef.add_recipe('Relativity::pre_relativity_copy_install_response_files_relativity')
  #   chef.add_recipe('Relativity::pre_relativity_copy_install_response_files_invariant')
  # end

  # # Run Pre-Relativity Chef Recipe
  # config.vm.provision 'chef_zero' do |chef|
  #   chef.cookbooks_path = 'Cookbooks'
  #   chef.data_bags_path = 'DataBags'
  #   chef.nodes_path = 'Nodes'
  #   chef.roles_path = 'Roles'
  #   chef.channel = 'stable'
  #   chef.version = '13.8.5'
  #   chef.json = {
  #     'smb_domain' => network_share_smb_domain,
  #     'smb_username' => network_share_smb_username,
  #     'smb_password' => network_share_smb_password,
  #     'smtp_server' => relativity_smtp_server,
  #     'smtp_port' => relativity_smtp_port,
  #     'email_from' => relativity_email_from,
  #     'email_to' => relativity_email_to,
  #   }
  #   chef.add_recipe('Relativity::default_pre_relativity')
  # end

  # # Restart VM
  # config.vm.provision :reload

  # # Make sure services are running
  # config.vm.provision 'chef_zero' do |chef|
  #   chef.cookbooks_path = 'Cookbooks'
  #   chef.data_bags_path = 'DataBags'
  #   chef.nodes_path = 'Nodes'
  #   chef.roles_path = 'Roles'
  #   chef.channel = 'stable'
  #   chef.version = '13.8.5'
  #   chef.json = {
  #     'smb_domain' => network_share_smb_domain,
  #     'smb_username' => network_share_smb_username,
  #     'smb_password' => network_share_smb_password,
  #     'smtp_server' => relativity_smtp_server,
  #     'smtp_port' => relativity_smtp_port,
  #     'email_from' => relativity_email_from,
  #     'email_to' => relativity_email_to,
  #   }
  #   chef.add_recipe('Relativity::default_start_services')
  # end

  # # Run Pre-Relativity Install Secret Store
  # config.vm.provision 'chef_zero' do |chef|
  #   chef.cookbooks_path = 'Cookbooks'
  #   chef.data_bags_path = 'DataBags'
  #   chef.nodes_path = 'Nodes'
  #   chef.roles_path = 'Roles'
  #   chef.channel = 'stable'
  #   chef.version = '13.8.5'
  #   chef.json = {
  #     'smb_domain' => network_share_smb_domain,
  #     'smb_username' => network_share_smb_username,
  #     'smb_password' => network_share_smb_password,
  #     'smtp_server' => relativity_smtp_server,
  #     'smtp_port' => relativity_smtp_port,
  #     'email_from' => relativity_email_from,
  #     'email_to' => relativity_email_to,
  #   }
  #   chef.add_recipe('Relativity::pre_relativity_secret_store_install')
  #   # chef.add_recipe('Relativity::pre_relativity_secret_store_install_save_secret_store_unseal_key_to_local_file') #has defect. so failing. need to be fixed.
  #   chef.add_recipe('Relativity::pre_relativity_secret_store_add_response_file_properties')
  # end

  # # Run Relativity Chef Recipe
  # config.vm.provision 'chef_zero' do |chef|
  #   chef.cookbooks_path = 'Cookbooks'
  #   chef.data_bags_path = 'DataBags'
  #   chef.nodes_path = 'Nodes'
  #   chef.roles_path = 'Roles'
  #   chef.channel = 'stable'
  #   chef.version = '13.8.5'
  #   chef.json = {
  #     'smb_domain' => network_share_smb_domain,
  #     'smb_username' => network_share_smb_username,
  #     'smb_password' => network_share_smb_password,
  #     'smtp_server' => relativity_smtp_server,
  #     'smtp_port' => relativity_smtp_port,
  #     'email_from' => relativity_email_from,
  #     'email_to' => relativity_email_to,
  #   }
  #   chef.add_recipe('Relativity::default_relativity')
  # end

  # # Restart VM
  # config.vm.provision :reload

  # # Make sure services are running
  # config.vm.provision 'chef_zero' do |chef|
  #   chef.cookbooks_path = 'Cookbooks'
  #   chef.data_bags_path = 'DataBags'
  #   chef.nodes_path = 'Nodes'
  #   chef.roles_path = 'Roles'
  #   chef.channel = 'stable'
  #   chef.version = '13.8.5'
  #   chef.json = {
  #     'smb_domain' => network_share_smb_domain,
  #     'smb_username' => network_share_smb_username,
  #     'smb_password' => network_share_smb_password,
  #     'smtp_server' => relativity_smtp_server,
  #     'smtp_port' => relativity_smtp_port,
  #     'email_from' => relativity_email_from,
  #     'email_to' => relativity_email_to,
  #   }
  #   chef.add_recipe('Relativity::default_start_services')
  # end

  # # Run Relativity Chef Recipe
  # config.vm.provision 'chef_zero' do |chef|
  #   chef.cookbooks_path = 'Cookbooks'
  #   chef.data_bags_path = 'DataBags'
  #   chef.nodes_path = 'Nodes'
  #   chef.roles_path = 'Roles'
  #   chef.channel = 'stable'
  #   chef.version = '13.8.5'
  #   chef.json = {
  #     'smb_domain' => network_share_smb_domain,
  #     'smb_username' => network_share_smb_username,
  #     'smb_password' => network_share_smb_password,
  #     'smtp_server' => relativity_smtp_server,
  #     'smtp_port' => relativity_smtp_port,
  #     'email_from' => relativity_email_from,
  #     'email_to' => relativity_email_to,
  #   }
  #   chef.add_recipe('Relativity::relativity_install_invariant')
  #   chef.add_recipe('Relativity::post_relativity_instance_setting_update_smtp_email_settings')
  #   # chef.add_recipe('Relativity::post_relativity_instance_setting_update_turn_telemetry_off')
  # end

  # # Restart VM
  # config.vm.provision :reload

  # # Make sure services are running
  # config.vm.provision 'chef_zero' do |chef|
  #   chef.cookbooks_path = 'Cookbooks'
  #   chef.data_bags_path = 'DataBags'
  #   chef.nodes_path = 'Nodes'
  #   chef.roles_path = 'Roles'
  #   chef.channel = 'stable'
  #   chef.version = '13.8.5'
  #   chef.json = {
  #     'smb_domain' => network_share_smb_domain,
  #     'smb_username' => network_share_smb_username,
  #     'smb_password' => network_share_smb_password,
  #     'smtp_server' => relativity_smtp_server,
  #     'smtp_port' => relativity_smtp_port,
  #     'email_from' => relativity_email_from,
  #     'email_to' => relativity_email_to,
  #   }
  #   chef.add_recipe('Relativity::default_start_services')
  # end

  # # Configure Distributed Servers
  # config.vm.provision 'chef_zero' do |chef|
  #   chef.cookbooks_path = 'Cookbooks'
  #   chef.data_bags_path = 'DataBags'
  #   chef.nodes_path = 'Nodes'
  #   chef.roles_path = 'Roles'
  #   chef.channel = 'stable'
  #   chef.version = '13.8.5'
  #   chef.json = {
  #     'smb_domain' => network_share_smb_domain,
  #     'smb_username' => network_share_smb_username,
  #     'smb_password' => network_share_smb_password,
  #     'smtp_server' => relativity_smtp_server,
  #     'smtp_port' => relativity_smtp_port,
  #     'email_from' => relativity_email_from,
  #     'email_to' => relativity_email_to,
  #   }
  #   chef.add_recipe('Relativity::post_relativity_sqlserver_distributed_link_servers')
  #   chef.add_recipe('Relativity::post_relativity_sqlserver_distributed_relativity_install')
  # end

  # # DataGrid Pre-setup
  # config.vm.provision 'chef_zero' do |chef|
  #   chef.cookbooks_path = 'Cookbooks'
  #   chef.data_bags_path = 'DataBags'
  #   chef.nodes_path = 'Nodes'
  #   chef.roles_path = 'Roles'
  #   chef.channel = 'stable'
  #   chef.version = '13.8.5'
  #   chef.json = {
  #     'smb_domain' => network_share_smb_domain,
  #     'smb_username' => network_share_smb_username,
  #     'smb_password' => network_share_smb_password,
  #     'smtp_server' => relativity_smtp_server,
  #     'smtp_port' => relativity_smtp_port,
  #     'email_from' => relativity_email_from,
  #     'email_to' => relativity_email_to,
  #   }
  #   chef.add_recipe('Relativity::post_relativity_Install_datagrid-presetup')
  # end

  # # Install DataGrid
  # config.vm.provision 'chef_zero' do |chef|
  #   chef.cookbooks_path = 'Cookbooks'
  #   chef.data_bags_path = 'DataBags'
  #   chef.nodes_path = 'Nodes'
  #   chef.roles_path = 'Roles'
  #   chef.channel = 'stable'
  #   chef.version = '13.8.5'
  #   chef.json = {
  #     'smb_domain' => network_share_smb_domain,
  #     'smb_username' => network_share_smb_username,
  #     'smb_password' => network_share_smb_password,
  #     'smtp_server' => relativity_smtp_server,
  #     'smtp_port' => relativity_smtp_port,
  #     'email_from' => relativity_email_from,
  #     'email_to' => relativity_email_to,
  #   }
  #   chef.add_recipe('Relativity::post_relativity_Install_datagrid')
  #   chef.add_recipe('Relativity::post_relativity_instance_setting_update_datagridendpoint')
  # end

  # # Add processing choice which is used in the following Invariant Configuration scripts below
  # config.vm.provision 'chef_zero' do |chef|
  #   chef.cookbooks_path = 'Cookbooks'
  #   chef.data_bags_path = 'DataBags'
  #   chef.nodes_path = 'Nodes'
  #   chef.roles_path = 'Roles'
  #   chef.channel = 'stable'
  #   chef.version = '13.8.5'
  #   chef.json = {
  #     'smb_domain' => network_share_smb_domain,
  #     'smb_username' => network_share_smb_username,
  #     'smb_password' => network_share_smb_password,
  #     'smtp_server' => relativity_smtp_server,
  #     'smtp_port' => relativity_smtp_port,
  #     'email_from' => relativity_email_from,
  #     'email_to' => relativity_email_to,
  #   }
  #   chef.add_recipe('Relativity::post_relativity_configure_invariant_create_processing_choice')
  # end

  # # Configure Invariant Configuration
  # config.vm.provision 'chef_zero' do |chef|
  #   chef.cookbooks_path = 'Cookbooks'
  #   chef.data_bags_path = 'DataBags'
  #   chef.nodes_path = 'Nodes'
  #   chef.roles_path = 'Roles'
  #   chef.channel = 'stable'
  #   chef.version = '13.8.5'
  #   chef.json = {
  #     'smb_domain' => network_share_smb_domain,
  #     'smb_username' => network_share_smb_username,
  #     'smb_password' => network_share_smb_password,
  #     'smtp_server' => relativity_smtp_server,
  #     'smtp_port' => relativity_smtp_port,
  #     'email_from' => relativity_email_from,
  #     'email_to' => relativity_email_to,
  #   }
  #   chef.add_recipe('Relativity::post_relativity_configure_invariant_create_worker_manager_server')
  #   chef.add_recipe('Relativity::post_relativity_configure_invariant_add_processing_to_default_resource_pool')
  #   chef.add_recipe('Relativity::post_relativity_configure_invariant_add_agent_and_worker_servers_to_default_resource_pool')
  #   chef.add_recipe('Relativity::post_relativity_configure_invariant_update_worker_server_for_processing')
  # end

  # # Restart VM
  # config.vm.provision :reload

  # # Make sure services are running
  # config.vm.provision 'chef_zero' do |chef|
  #   chef.cookbooks_path = 'Cookbooks'
  #   chef.data_bags_path = 'DataBags'
  #   chef.nodes_path = 'Nodes'
  #   chef.roles_path = 'Roles'
  #   chef.channel = 'stable'
  #   chef.version = '13.8.5'
  #   chef.json = {
  #     'smb_domain' => network_share_smb_domain,
  #     'smb_username' => network_share_smb_username,
  #     'smb_password' => network_share_smb_password,
  #     'smtp_server' => relativity_smtp_server,
  #     'smtp_port' => relativity_smtp_port,
  #     'email_from' => relativity_email_from,
  #     'email_to' => relativity_email_to,
  #   }
  #   chef.add_recipe('Relativity::default_start_services')
  # end

  # # Run Post-Relativity Recipes
  # config.vm.provision 'chef_zero' do |chef|
  #   chef.cookbooks_path = 'Cookbooks'
  #   chef.data_bags_path = 'DataBags'
  #   chef.nodes_path = 'Nodes'
  #   chef.roles_path = 'Roles'
  #   chef.channel = 'stable'
  #   chef.version = '13.8.5'
  #   chef.json = {
  #     'smb_domain' => network_share_smb_domain,
  #     'smb_username' => network_share_smb_username,
  #     'smb_password' => network_share_smb_password,
  #     'smtp_server' => relativity_smtp_server,
  #     'smtp_port' => relativity_smtp_port,
  #     'email_from' => relativity_email_from,
  #     'email_to' => relativity_email_to,
  #   }
  #   chef.add_recipe('Relativity::post_relativity_instance_setting_update_developer_mode')
  #   chef.add_recipe('Relativity::post_relativity_reset_iis')
  #   chef.add_recipe('Relativity::post_relativity_update_kcura_services_startup_type')
  #   chef.add_recipe('Relativity::post_relativity_create_workspace')
  #   chef.add_recipe('Relativity::post_relativity_create_data_sampler_config_file')
  #   chef.add_recipe('Relativity::post_relativity_push_resource_file')
  #   chef.add_recipe('Relativity::post_relativity_install_rap_files')
  #   # chef.add_recipe('Relativity::post_relativity_create_rap_agents') #agent api discontinued. so failing. need to be fixed.
  # end

  # # Cleanup VM
  # config.vm.provision 'chef_zero' do |chef|
  #   chef.cookbooks_path = 'Cookbooks'
  #   chef.data_bags_path = 'DataBags'
  #   chef.nodes_path = 'Nodes'
  #   chef.roles_path = 'Roles'
  #   chef.channel = 'stable'
  #   chef.version = '13.8.5'
  #   chef.json = {
  #     'smb_domain' => network_share_smb_domain,
  #     'smb_username' => network_share_smb_username,
  #     'smb_password' => network_share_smb_password,
  #     'smtp_server' => relativity_smtp_server,
  #     'smtp_port' => relativity_smtp_port,
  #     'email_from' => relativity_email_from,
  #     'email_to' => relativity_email_to,
  #   }
  #   chef.add_recipe('Relativity::post_relativity_cleanup')
  #   chef.add_recipe('Relativity::post_relativity_write_script_result_success')
  # end

  # # Remove any chef.json variables from the VM
  # # Note: Remember to add any chef.json variables to this last vagrant block to clear those values on the VM once its created
  # config.vm.provision 'chef_zero' do |chef|
  #   chef.cookbooks_path = 'Cookbooks'
  #   chef.data_bags_path = 'DataBags'
  #   chef.nodes_path = 'Nodes'
  #   chef.roles_path = 'Roles'
  #   chef.channel = 'stable'
  #   chef.version = '13.8.5'
  #   chef.json = {
  #     'smb_domain' => '',
  #     'smb_username' => '',
  #     'smb_password' => '',
  #     'smtp_server' => '',
  #     'smtp_port' => '',
  #     'email_from' => '',
  #     'email_to' => '',
  #   }
  # end
end
